引用内容错误修复
tufanbarisyildirim/php-apk-parser pull request #91
Opened 2020-09-01 13:15 UTC by songliqun

多次引用地址内容反过来导致获取空了

2020-10-09 09:59 UTC, JoeZing commented
兄die，老外看不懂中文的

2020-12-31 02:45 UTC, syncing0x requested changes
``

2021-08-20 21:59 UTC, tufanbarisyildirim commented
not sure what does this change do.

2022-02-12 07:54 UTC, songliqun commented
putReferenceResource 这个方法第一个参数应该传地址，第二个参数应该传内容。现在两个参数传反了，会导致取不到正确内容的！

2022-11-28 13:38 UTC, closed without merging